
call  c:\cmsc\setenv.bat x64

set JAVA_HOME=D:\java\jdk1.8.0_144
set OPENSSL_VER=3.0.13
set APR_VER=1.7.4
set WINVER=WIN7
rem nmake -f NMAKEMakefile WITH_APR=C:\deps-x86\apr-%APR_VER% WITH_OPENSSL=C:\deps-x86\openssl-%OPENSSL_VER% APR_DECLARE_STATIC=1 OPENSSL_NEW_LIBS=0  ENABLE_OCSP=1
nmake -f NMAKEMakefile WITH_APR=C:\deps-x64\apr-%APR_VER% WITH_OPENSSL=C:\deps-x64\openssl-%OPENSSL_VER% APR_DECLARE_STATIC=1 OPENSSL_NEW_LIBS=0 ENABLE_OCSP=1
move WIN7_X64_DLL_RELEASE WIN7_X64_OCSP_DLL_RELEASE


 
move WIN7_X86_DLL_RELEASE WIN7_X86_OCSP_DLL_RELEASE
nmake -f NMAKEMakefile WITH_APR=C:\deps-x64\apr-%APR_VER% WITH_OPENSSL=C:\deps-x64\openssl-%OPENSSL_VER% APR_DECLARE_STATIC=1 OPENSSL_NEW_LIBS=0

pause