
call c:\cmsc\setenv.bat x86

set JAVA_HOME=D:\java\jdk1.8.0_144
set OPENSSL_VER=1.1.1k
set APR_VER=1.7.4
set WINVER=WIN7
nmake -f NMAKEMakefile WITH_APR=C:\deps-x86\apr-%APR_VER% WITH_OPENSSL=C:\deps-x86\openssl-%OPENSSL_VER% APR_DECLARE_STATIC=1 OPENSSL_NEW_LIBS=0 BUILD_CPU=x86 ENABLE_OCSP=1

pause 
ENABLE_OCSP=1
move WIN7_X86_DLL_RELEASE WIN7_X86_OCSP_DLL_RELEASE
nmake -f NMAKEMakefile WITH_APR=C:\deps-x86\apr-%APR_VER% WITH_OPENSSL=C:\deps-x86\openssl-%OPENSSL_VER% APR_DECLARE_STATIC=1 OPENSSL_NEW_LIBS=0 BUILD_CPU=x86 ENABLE_OCSP=1

pause

